[package]
name = "rview"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22.0"
egui_extras = { version = "0.22.0", features = ["image"] }
futures = "0.3.28"
image = "0.24.7"
infer = "0.15.0"
reqwest = "0.11.18"
rfd = "0.11.4"
serde = { version = "1.0.183", features = ["derive"] }
